import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { MainLayout } from "~/components/layout/main-layout";
import { AuthSessionProvider } from "~/components/auth/session-provider";
import { NavigationProvider } from "~/contexts/navigation-context";

export const metadata: Metadata = {
  title: "In-It",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} dark`}>
      <body suppressHydrationWarning={true}>
        <AuthSessionProvider>
          <NavigationProvider>
            <MainLayout>
              <TRPCReactProvider>{children}</TRPCReactProvider>
            </MainLayout>
          </NavigationProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
